"""Parsing e validação de respostas da OpenAI.

Responsabilidades:
- Extrair JSON de respostas (com tratamento de erros)
- Validar e converter para contratos tipados
- Fornecer fallbacks determinísticos quando LLM falha
"""

from __future__ import annotations

import json
import logging
from typing import Any

from pyloto_corp.ai.contracts.event_detection import EventDetectionResult
from pyloto_corp.ai.contracts.message_type_selection import MessageTypeSelectionResult
from pyloto_corp.ai.contracts.response_generation import ResponseGenerationResult
from pyloto_corp.domain.session.events import SessionEvent

logger = logging.getLogger(__name__)


def parse_event_detection_response(raw_response: str) -> EventDetectionResult:
    """Parse resposta de event detection."""
    try:
        data = _extract_json_from_response(raw_response)

        # Validação mínima
        event_str = data.get("event", "USER_SENT_TEXT").upper()
        if event_str in SessionEvent.__members__:
            event = SessionEvent[event_str]
        else:
            event = SessionEvent.USER_SENT_TEXT

        return EventDetectionResult(
            event=event,
            detected_intent=data.get("detected_intent", "ENTRY_UNKNOWN"),
            confidence=float(data.get("confidence", 0.5)),
            requires_followup=bool(data.get("requires_followup", False)),
            rationale=data.get("rationale", "Parsed from LLM response"),
        )
    except Exception as e:
        logger.warning(
            "event_detection_parse_failed",
            extra={"error": str(e), "error_type": type(e).__name__},
        )
        return _fallback_event_detection()


def parse_response_generation_response(raw_response: str) -> ResponseGenerationResult:
    """Parse resposta de response generation."""
    try:
        data = _extract_json_from_response(raw_response)

        text_content = data.get("text_content", "")
        options = data.get("options", [])

        # Validação: truncar se muito longo
        if len(text_content) > 4096:
            text_content = text_content[:4093] + "..."

        return ResponseGenerationResult(
            text_content=text_content,
            options=options,
            suggested_next_state=data.get("suggested_next_state"),
            requires_human_review=bool(data.get("requires_human_review", False)),
            confidence=float(data.get("confidence", 0.7)),
            rationale=data.get("rationale", "Generated by LLM"),
        )
    except Exception as e:
        logger.warning(
            "response_generation_parse_failed",
            extra={"error": str(e), "error_type": type(e).__name__},
        )
        return _fallback_response_generation()


def parse_message_type_response(raw_response: str) -> MessageTypeSelectionResult:
    """Parse resposta de message type selection."""
    try:
        data = _extract_json_from_response(raw_response)

        message_type = data.get("message_type", "TEXT").upper()
        parameters = data.get("parameters", {})

        return MessageTypeSelectionResult(
            message_type=message_type,
            parameters=parameters,
            confidence=float(data.get("confidence", 0.6)),
            rationale=data.get("rationale", "Selected by LLM"),
            fallback=False,
        )
    except Exception as e:
        logger.warning(
            "message_type_parse_failed",
            extra={"error": str(e), "error_type": type(e).__name__},
        )
        return _fallback_message_type_selection()


def _extract_json_from_response(response: str) -> dict[str, Any]:
    """Extrai e valida JSON de resposta."""
    if not response or not isinstance(response, str):
        raise ValueError("Response é vazio ou não é string")

    # Limpar markdown code blocks se presentes
    response = response.strip()
    if response.startswith("```json"):
        response = response[7:]
    if response.startswith("```"):
        response = response[3:]
    if response.endswith("```"):
        response = response[:-3]

    response = response.strip()
    data = json.loads(response)

    if not isinstance(data, dict):
        raise ValueError("Response não é um JSON object")

    return data


def _fallback_event_detection() -> EventDetectionResult:
    """Fallback determinístico para event detection."""
    return EventDetectionResult(
        event=SessionEvent.USER_SENT_TEXT,
        detected_intent="ENTRY_UNKNOWN",
        confidence=0.3,
        requires_followup=True,
        rationale="Fallback: LLM event detection falhou",
    )


def _fallback_response_generation() -> ResponseGenerationResult:
    """Fallback determinístico para response generation."""
    return ResponseGenerationResult(
        text_content="Desculpe, não consegui processar sua mensagem. Poderia reformular?",
        options=[],
        suggested_next_state=None,
        requires_human_review=True,
        confidence=0.2,
        rationale="Fallback: LLM response generation falhou",
    )


def _fallback_message_type_selection() -> MessageTypeSelectionResult:
    """Fallback determinístico para message type selection."""
    return MessageTypeSelectionResult(
        message_type="TEXT",
        parameters={},
        confidence=0.1,
        rationale="Fallback: LLM message type selection falhou",
        fallback=True,
    )
